/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package moodlesystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Hardkiller
 */
public class adminFrame extends javax.swing.JFrame {

    /**
     * Creates new form adminFrame
     */
    String userName;
    int userRole;
    Connection dbConnection;
    Statement statement;
    public adminFrame(String userName, int userRole, Connection dbConnection) {
        initComponents();
        //System.out.println("Hi, Welcome to Tabbed Pane...!!!");
        btnAddUser.setVisible(false);
        btnSearchUser.setVisible(false);
        pnlAddUser.setVisible(false);
        pnlSearch.setVisible(false);
        lblErrorMessage.setVisible(false);
        lblErrorMessage.setForeground(Color.red);
        this.userName = userName;
        this.userRole = userRole;
        this.dbConnection = dbConnection;
        lblWelcomeMessage.setForeground(Color.red);
        lblWelcomeMessage.setText("Welcome to Moodle: " + userName + "...!!!");
        if (userRole == 1)
        {
            btnAddUser.setVisible(true);
            btnSearchUser.setVisible(true);
        }
    }
    
    public adminFrame() {
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdminFrame = new javax.swing.JPanel();
        jtpMainView = new javax.swing.JTabbedPane();
        pnlUserFunctionality = new javax.swing.JPanel();
        btnAddUser = new javax.swing.JButton();
        btnSearchUser = new javax.swing.JButton();
        pnlAddUser = new javax.swing.JPanel();
        lblUserID = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserRole = new javax.swing.JLabel();
        lblUserActive = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        chkUserRole = new javax.swing.JCheckBox();
        cmbUserRole = new javax.swing.JComboBox();
        btnCreate = new javax.swing.JButton();
        lblErrorMessage = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblWelcomeMessage = new javax.swing.JLabel();
        pnlSearch = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnGo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        btnAddUser.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnAddUser.setText("Add");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnSearchUser.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnSearchUser.setText("Search");
        btnSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchUserActionPerformed(evt);
            }
        });

        pnlAddUser.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter User Details"));

        lblUserID.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblUserID.setText("User ID: ");

        lblUserName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblUserName.setText("User Name: ");

        lblUserRole.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblUserRole.setText("User Role: ");

        lblUserActive.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblUserActive.setText("User Active: ");

        txtUserID.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtUserID.setToolTipText("Enter User ID");

        txtUserName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtUserName.setToolTipText("Enter User Name");
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        chkUserRole.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        chkUserRole.setToolTipText("Check User Activity");

        cmbUserRole.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cmbUserRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Instructors", "Students" }));
        cmbUserRole.setToolTipText("Select User Role");

        btnCreate.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.setToolTipText("Click to Create User");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblErrorMessage.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnClear.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setToolTipText("Click to Update Record");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("Click to Delete Record");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddUserLayout = new javax.swing.GroupLayout(pnlAddUser);
        pnlAddUser.setLayout(pnlAddUserLayout);
        pnlAddUserLayout.setHorizontalGroup(
            pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddUserLayout.createSequentialGroup()
                        .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserID)
                            .addComponent(lblUserName)
                            .addComponent(lblUserRole)
                            .addComponent(lblUserActive))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkUserRole)
                            .addComponent(cmbUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlAddUserLayout.createSequentialGroup()
                                .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCancel))))
                        .addContainerGap(134, Short.MAX_VALUE))
                    .addGroup(pnlAddUserLayout.createSequentialGroup()
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)))
        );
        pnlAddUserLayout.setVerticalGroup(
            pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddUserLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserID)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserName)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserRole))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserActive)
                    .addComponent(chkUserRole))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        lblWelcomeMessage.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        pnlSearch.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        lblSearch.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblSearch.setText("Search:");

        txtSearch.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnGo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnGo.setText("Go");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSearchLayout = new javax.swing.GroupLayout(pnlSearch);
        pnlSearch.setLayout(pnlSearchLayout);
        pnlSearchLayout.setHorizontalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSearchLayout.setVerticalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGo)))
        );

        javax.swing.GroupLayout pnlUserFunctionalityLayout = new javax.swing.GroupLayout(pnlUserFunctionality);
        pnlUserFunctionality.setLayout(pnlUserFunctionalityLayout);
        pnlUserFunctionalityLayout.setHorizontalGroup(
            pnlUserFunctionalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserFunctionalityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserFunctionalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserFunctionalityLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblWelcomeMessage))
                    .addGroup(pnlUserFunctionalityLayout.createSequentialGroup()
                        .addGroup(pnlUserFunctionalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlUserFunctionalityLayout.createSequentialGroup()
                                .addComponent(btnAddUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchUser)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlUserFunctionalityLayout.setVerticalGroup(
            pnlUserFunctionalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserFunctionalityLayout.createSequentialGroup()
                .addComponent(lblWelcomeMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUserFunctionalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearchUser)
                    .addComponent(btnAddUser))
                .addGap(15, 15, 15)
                .addComponent(pnlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpMainView.addTab("Users", null, pnlUserFunctionality, "User Details");

        javax.swing.GroupLayout pnlAdminFrameLayout = new javax.swing.GroupLayout(pnlAdminFrame);
        pnlAdminFrame.setLayout(pnlAdminFrameLayout);
        pnlAdminFrameLayout.setHorizontalGroup(
            pnlAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpMainView)
        );
        pnlAdminFrameLayout.setVerticalGroup(
            pnlAdminFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpMainView, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        jtpMainView.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAdminFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAdminFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:#
        pnlAddUser.setVisible(true);
        txtUserID.setText("");
        txtUserName.setText("");
        cmbUserRole.setSelectedIndex(0);
        chkUserRole.setSelected(false);
        txtUserID.setEditable(true);
        txtUserName.setEditable(true);
        cmbUserRole.setEnabled(true);
        chkUserRole.setEnabled(true);
        lblErrorMessage.setText("");
        lblErrorMessage.setVisible(false);
        btnCreate.setEnabled(true);
        btnAddUser.setEnabled(false);
        btnSearchUser.setEnabled(false);
        btnUpdate.setVisible(false);
        btnDelete.setVisible(false);
        btnCreate.setText("Create");
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        
        if (btnCreate.getText().equals("Create"))
        {
            String userID = txtUserID.getText().trim();
            String userName = txtUserName.getText().trim();
            String userRole = cmbUserRole.getSelectedItem().toString();
            int userActive;
            int userRoleValue;
            boolean userActivity = chkUserRole.isSelected();
            //System.out.println("User ID ====> " + userID + "...!!!");
            //System.out.println("User Name ==> " + userName + "...!!!");
            //System.out.println("User Role ==> " + userRole + "...!!!");
            //System.out.println("User Activity ==> " + userActivity + "...!!!");

            if (userID.length() == 0)
            {
                lblErrorMessage.setVisible(true);
                lblErrorMessage.setText("Enter User ID");
            }
            else if(userName.length() == 0)
            {
                lblErrorMessage.setVisible(true);
                lblErrorMessage.setText("Enter User Name");
            }
            if (userActivity)
            {
                userActive = 1;
            }
            else
            {
                userActive = 0;
            }
            if (userRole.equals("Admin"))
            {
                userRoleValue = 1;
            }
            else if (userRole.equals("Instructors"))
            {
                userRoleValue = 2;
            }
            else 
            {
                userRoleValue = 3;
            }
            if (dbConnection != null)
            {
                try
                {

                    String insertUserRecord = "INSERT INTO USERS (USERID, USERNAME, USERROLE, USERFLAG, USERPASSWORD)" +
                        " VALUES ('" + userID + "', '" + userName + "', '" + userRoleValue + "', '" + 
                        userActive + "', '" + userName.toUpperCase() + "')";
                    statement = dbConnection.createStatement();
                    if (!statement.execute(insertUserRecord))
                    {
                        System.out.println("Adding Record for User " + userName + " was successfully completed...!!!");
                        lblErrorMessage.setVisible(true);
                        lblErrorMessage.setText("Adding Record for User " + userName + " was successfully completed...!!!");
                        txtUserID.setEditable(false);
                        txtUserName.setEditable(false);
                        cmbUserRole.setEnabled(false);
                        chkUserRole.setEnabled(false);
                        btnCreate.setEnabled(false);
                        btnAddUser.setEnabled(true);
                        btnSearchUser.setEnabled(true);
                    }
                    else
                    {
                            System.out.println("Adding Record for User " + userName + " was unsuccessfully...!!!");
                            lblErrorMessage.setVisible(true);
                            lblErrorMessage.setText("Adding Record for User " + userName + " was unsuccessfully...!!!");
                    }
                }
                catch(Exception e)
                {
                    System.out.println(e.getMessage());
                }
            }
        }
        else if (btnCreate.getText().equals("Edit"))
        {
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(false);
            btnClear.setEnabled(true);
            txtUserName.setEditable(true);
            cmbUserRole.setEnabled(true);
            chkUserRole.setEnabled(true);
            btnCreate.setEnabled(false);
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(false);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchUserActionPerformed
        pnlAddUser.setVisible(false);
        pnlSearch.setVisible(true);
        txtUserID.setText("");
        txtUserName.setText("");
        cmbUserRole.setSelectedIndex(0);
        chkUserRole.setSelected(false);
        txtUserID.setEditable(true);
        txtUserName.setEditable(true);
        cmbUserRole.setEnabled(true);
        chkUserRole.setEnabled(true);
        lblErrorMessage.setText("");
        lblErrorMessage.setVisible(false);
        btnCreate.setEnabled(true);
        btnAddUser.setEnabled(false);
        btnSearchUser.setEnabled(false);
    }//GEN-LAST:event_btnSearchUserActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        try
        {
            String searchID = txtSearch.getText();
            Statement statement = dbConnection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            //ResultSet resultSet = statement.executeQuery("select userid, username, userrole, userflag from users where userid = '" + searchID + "'") ;
            ResultSet resultSet = statement.executeQuery("select * from users where userid = '" + searchID + "'") ;
            
            if (resultSet.next())
            {
                System.out.println("User ID ====> " + resultSet.getString("userid") + "...!!!");
                System.out.println("User Name ==> " + resultSet.getString("username") + "...!!!");
                System.out.println("User Role ==> " + (resultSet.getInt("userRole")-1) + "...!!!");
                System.out.println("User Activity ==> " + resultSet.getInt("userflag") + "...!!!");
                txtUserID.setText(resultSet.getString("userid"));
                txtUserName.setText(resultSet.getString("username"));
                cmbUserRole.setSelectedIndex(resultSet.getInt("userrole")-1);
                if (resultSet.getInt("userflag") == 0)
                    chkUserRole.setSelected(false);
                else
                    chkUserRole.setSelected(true);
            }
            pnlAddUser.setVisible(true);
            btnCreate.setText("Edit");
            txtUserID.setEditable(false);
            txtUserName.setEditable(false);
            cmbUserRole.setEnabled(false);
            chkUserRole.setEnabled(false);
            btnUpdate.setVisible(true);
            btnDelete.setVisible(true);
            btnUpdate.setEnabled(false);
            btnClear.setEnabled(false);
        }
        catch (Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnGoActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        pnlAddUser.setVisible(false);
        pnlSearch.setVisible(false);
        btnAddUser.setEnabled(true);
        btnSearchUser.setEnabled(true);
        txtSearch.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String userID = txtUserID.getText().trim();
        if (dbConnection != null)
        {
            try
            {
                String updateUserRecord = "DELETE FROM USERS WHERE USERID = '" + userID + "'";
                statement = dbConnection.createStatement();
                if (!statement.execute(updateUserRecord))
                {
                    JOptionPane.showMessageDialog(this, userID + " User is deleted from database...!!!", "User Deleted", JOptionPane.OK_OPTION );
                    pnlAddUser.setVisible(false);
                    pnlSearch.setVisible(false);
                    btnSearchUser.setEnabled(true);
                    btnAddUser.setEnabled(true);
                    
                }
            }
            catch(Exception e)
            {
                System.out.println(e.getMessage());
            }
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        if (btnCreate.getText().equals("Create"))
        {
            txtUserID.setText("");
        }
        txtUserName.setText("");
        cmbUserRole.setSelectedIndex(0);
        chkUserRole.setSelected(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String userID = txtUserID.getText().trim();
        String userName = txtUserName.getText().trim();
        String userRole = cmbUserRole.getSelectedItem().toString();
        int userActive;
        int userRoleValue;
        boolean userActivity = chkUserRole.isSelected();
        //System.out.println("User ID ====> " + userID + "...!!!");
        //System.out.println("User Name ==> " + userName + "...!!!");
        //System.out.println("User Role ==> " + userRole + "...!!!");
        //System.out.println("User Activity ==> " + userActivity + "...!!!");

        if (userID.length() == 0)
        {
            //lblErrorMessage.setVisible(true);
            JOptionPane.showMessageDialog(this, "Enter User ID...!!!", "Message", JOptionPane.OK_OPTION );
            //lblErrorMessage.setText("Enter User ID");
        }
        else if(userName.length() == 0)
        {
            lblErrorMessage.setVisible(true);
            lblErrorMessage.setText("Enter User Name");
        }
        if (userActivity)
        {
            userActive = 1;
        }
        else
        {
            userActive = 0;
        }
        if (userRole.equals("Admin"))
        {
            userRoleValue = 1;
        }
        else if (userRole.equals("Instructors"))
        {
            userRoleValue = 2;
        }
        else 
        {
            userRoleValue = 3;
        }
        if (dbConnection != null)
        {
            try
            {
                String updateUserRecord = "UPDATE USERS SET USERNAME = '" + userName + "', "
                        + "USERROLE = '" + userRoleValue + "', USERFLAG = '" + userActive + "' where "
                        + "USERID = '" + userID + "'";
                statement = dbConnection.createStatement();
                if (!statement.execute(updateUserRecord))
                {
                    System.out.println("Updating Record for User " + userName + " was successfully completed...!!!");
                    lblErrorMessage.setVisible(true);
                    lblErrorMessage.setText("Updating Record for User " + userName + " was successfully completed...!!!");
                    txtUserID.setEditable(false);
                    txtUserName.setEditable(false);
                    cmbUserRole.setEnabled(false);
                    chkUserRole.setEnabled(false);
                    btnCreate.setEnabled(false);
                    btnAddUser.setEnabled(true);
                    btnSearchUser.setEnabled(true);
                    btnUpdate.setEnabled(false);
                    btnCreate.setEnabled(true);
                    btnDelete.setEnabled(true);
                    btnClear.setEnabled(false);
                }
                else
                {
                        System.out.println("Updating Record for User " + userName + " was unsuccessfully...!!!");
                        lblErrorMessage.setVisible(true);
                        lblErrorMessage.setText("Updating Record for User " + userName + " was unsuccessfully...!!!");
                }
                
                
            }
            catch(Exception e)
            {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnSearchUser;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkUserRole;
    private javax.swing.JComboBox cmbUserRole;
    private javax.swing.JTabbedPane jtpMainView;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblUserActive;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserRole;
    private javax.swing.JLabel lblWelcomeMessage;
    private javax.swing.JPanel pnlAddUser;
    private javax.swing.JPanel pnlAdminFrame;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JPanel pnlUserFunctionality;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
