/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package moodlesystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Hardkiller
 */
public class loginForm extends javax.swing.JFrame {

    /**
     * Creates new form loginForm
     */
    public loginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUserLogin = new javax.swing.JPanel();
        lblMoodle = new javax.swing.JLabel();
        lblUserNameID = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        lblErrorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Moodle Login System");
        setName("loginFrame"); // NOI18N
        setResizable(false);

        lblMoodle.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        lblMoodle.setText("Moodle Login");

        lblUserNameID.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblUserNameID.setText("User Name/ID: ");

        lblPassword.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblPassword.setText("Password: ");

        txtUserName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtUserName.setToolTipText("Enter User Name/ID");

        btnLogin.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setToolTipText("Click Login To Move In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtPassword.setToolTipText("Enter Password");

        lblErrorMessage.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlUserLoginLayout = new javax.swing.GroupLayout(pnlUserLogin);
        pnlUserLogin.setLayout(pnlUserLoginLayout);
        pnlUserLoginLayout.setHorizontalGroup(
            pnlUserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(126, 126, 126))
            .addGroup(pnlUserLoginLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(pnlUserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorMessage)
                    .addComponent(lblMoodle)
                    .addGroup(pnlUserLoginLayout.createSequentialGroup()
                        .addComponent(lblUserNameID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUserLoginLayout.createSequentialGroup()
                        .addComponent(lblPassword)
                        .addGap(29, 29, 29)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        pnlUserLoginLayout.setVerticalGroup(
            pnlUserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserLoginLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblMoodle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserNameID)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErrorMessage)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUserLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUserLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        try 
        {
            lblErrorMessage.setVisible(false);
            String userName = txtUserName.getText().trim();
            String password =  txtPassword.getText().trim();
            System.out.println("Welcome User " + userName + "...!!!");
            System.out.println("Password: " + password + "...!!!");
            if (userName.length() == 0 && password.length() == 0)
            {
                lblErrorMessage.setVisible(true);
                lblErrorMessage.setForeground(Color.RED);
                lblErrorMessage.setText("Please Enter Username/Password");
                txtUserName.setFocusable(true);
            }
            else
            {
                Connection dbConnection = DatabaseUtils.connectDatabase();
                Statement statement = dbConnection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                ResultSet resultSet = statement.executeQuery("select userpassword, userrole from users where username = '" + userName + "'") ;
                if (resultSet.next() && resultSet.getString("userpassword").equals(password))
                {
                    int userRole = resultSet.getInt("userrole");
                    //System.out.println("Welcome User " + userName + "...!!!");
                    //lblErrorMessage.setVisible(true);
                    //lblErrorMessage.setForeground(Color.RED);
                    //lblErrorMessage.setText("Welcome User " + userName + "...!!!");
                    this.hide();
                    //welcomeScreen objWelcomeScreen = new welcomeScreen(userName);
                    //objWelcomeScreen.show();
                    adminFrame objAdminFrame = new adminFrame(userName, userRole, dbConnection);
                    objAdminFrame.show();
                    
                }
                else
                {
                    System.out.println("User Name/ID is incorrect...!!!");
                    lblErrorMessage.setVisible(true);
                    lblErrorMessage.setForeground(Color.RED);
                    lblErrorMessage.setText("User Name/ID is incorrect...!!!");
                }
                resultSet.close();
            }
        }
        catch(Exception e)
        {
            System.out.println("Error: " + e.getMessage());
        }    
    }//GEN-LAST:event_btnLoginActionPerformed

    
    
    //private static boolean validateUserDetails(String userName, String password)
    //{
     //   
    //}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblMoodle;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserNameID;
    private javax.swing.JPanel pnlUserLogin;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
